### ISSUE TITLE
Public Omi has its snapshot also public

### ISSUE THREAD

**Issue by outscale-vbr** [outscale/packer-plugin-outscale#112]
#### Overview of the Issue

I want to create a public omi with packer. But when omi is public its snapshot is also  public so every client  in the region has this snapshot and only the account which is associated with the accountId can delete it. So when we want to have a public omi its snapshot should be private.

#### Reproduction Steps
Have this parameters in your config:
```
      "global_permission": true,
      "omi_account_ids": [
        "0123456789"
      ],
```

### Plugin and Packer version

Packer v1.8.5
Packer Outscale plugins v1.0.5

### Operating system and Environment details
Ubuntu 20.04.3 LTS

**Comment by outscale-hmi** [comment]
PR done https://github.com/outscale/packer-plugin-outscale/pull/117
