### ISSUE TITLE
Missing global_permission in packer provider outscale plugin docs

### ISSUE THREAD

**Issue by outscale-vbr** [outscale/packer-plugin-outscale#123]
#### Overview of the Issue

There is no trace in documentation https://developer.hashicorp.com/packer/plugins/builders/outscale/bsu of global-permission even if it is available since packer provider outscale plugin v1.0.5

**Comment by outscale-hmi** [comment]
PR is done https://github.com/outscale/packer-plugin-outscale/pull/125
