### ISSUE TITLE
Please use semantic MAJOR.MINOR.PATCH accordingly

### ISSUE THREAD

**Issue by wibru** [outscale/packer-plugin-outscale#134]
Hi Outscale !

Beforehand, many thanks for the upgrade of the packer plugin.

You just released the 1.0.6 with a lot of major changes according to the diff. It breaks for me:
```
1680272967,,ui,error,Build 'outscale-bsu.default' errored after 1 millisecond 552 microseconds: Error querying OMI: The variable region in the server URL has invalid value . Must be [ap-northeast-1 cloudgouv-eu-west-1 eu-west-2 us-east-2 us-west-1]
```

I use constraints of this type in my configuration, and I believe that I should not have this kind of concern:
```
packer {
  required_plugins {
    outscale = {
      version = "~> 1.0.0"
      source  = "github.com/outscale/outscale"
    }
  }
}
```

Is it possible to be more vigilant about versioning in the future?

Regarding the bug, I still have to do some debugging but I lack of time before the weekend to check and open a bugreport if appropriate.

Thank you

**Comment by outscale-hmi** [comment]
Hello 
Sorry for the inconvenience.  
Can you give us more details regarding this bug ?

**Comment by outscale-hmi** [comment]
https://github.com/outscale/packer-plugin-outscale/pull/137
