### ISSUE TITLE
Breaking changes in go-cty

### ISSUE THREAD

**Issue by outscale-mdr** [outscale/packer-plugin-outscale#138]
In v1.11.0 of [github.com/zclconf/go-cty,](http://github.com/zclconf/go-cty,) encoding/gob support was removed from the package. The Packer plugin SDK relies on gob for supporting HCL2 templates. The removal of the encoding causes Packer to crash when using HCL2 templates.

The team and I are working internally to find the best path forward, as a change to the wire protocol from gob will introduce a breaking change and plugin incompatibilities. We are working to notify plugin developers of the incompatible go-cty package and ask that all external plugins pin the versions of the following two packages to those used by the Packer plugin SDK.

[github.com/hashicorp/hcl/v2](http://github.com/hashicorp/hcl/v2) v2.13.0
[github.com/zclconf/go-cty](http://github.com/zclconf/go-cty) v1.10.0

**Comment by outscale-toa** [comment]
Fixed on https://github.com/outscale/packer-plugin-outscale/pull/156
