### ISSUE TITLE
Add the new ProductCodes parameter as a configuration option

### ISSUE THREAD

**Issue by lourheroes** [outscale/packer-plugin-outscale#141]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

We would like to have a new parameter **ProductCodes** available in the Outscale plugin configuration.
This parameter must be only available for Image creation (not when updating Images)

#### Use Case(s)

This parameter will let users set one or multiple ProductCode to the Image they create with Packer
This option will be used by Outscale Marketplace partners that want to create and share their Image to other users.

#### Potential configuration

```
A new configuration option named ProductCodes
```

#### Potential References

[CreateImage OAPI Docs](https://docs.outscale.com/api#createimage)

**Comment by outscale-hmi** [comment]
https://github.com/outscale/packer-plugin-outscale/pull/142

**Comment by outscale-hmi** [comment]
Done
