### ISSUE TITLE
Source OMI filters

### ISSUE THREAD

**Issue by Dzibeul** [outscale/packer-plugin-outscale#151]
#### Overview of the Issue
The parameter `owners` in Source OMI filters stands for `Account alias` but not `account ID` like it is said in the documentation.

#### Reproduction Steps

I tried to get the source image lin my packer template like this :
`
source_omi_filter {
    filters = {
      image-name = "RockyLinux-8-2022.01.18-0"
    }
    owners = ["123456789125"]
 }
`

It doesn't find the image.

But when I tried this :

`
source_omi_filter {     
     filters = {       
        image-name = "RockyLinux-8-2022.01.18-0"     
     }
     owners = ["Outscale"]
}
`  

It works.

### Plugin and Packer version

From `1.1.1`

### Simplified Packer Buildfile

[Github detailed
format](https://gist.github.com/Dzibeul/d34f669f632a61ff6454bd172b868d8b)

### Operating system and Environment details

Rocky9.1, x86_64

**Comment by outscale-toa** [comment]
Hi @Dzibeul,
Thanks for reaching us, we are looking at your issue

Best regards,

**Comment by Dzibeul** [comment]
My bad, I installed the wrong version of packer (386 instead of AMD64)
