### ISSUE TITLE
Documentation on variable use inconsistent

### ISSUE THREAD

**Issue by Joseph94m** [outscale/packer-plugin-outscale#168]
Hello,

the documentation on https://developer.hashicorp.com/packer/plugins/builders/outscale/outscale-bsu states that the variable to specify the oapi endpoints is [custom_endpoint_oapi](https://developer.hashicorp.com/packer/plugins/builders/outscale/outscale-bsu#custom_endpoint_oapi).

On https://developer.hashicorp.com/packer/plugins/builders/outscale#authentication it shows `oapi_custom_endpoint`

Is this an alias or is it a typo?

**Comment by outscale-toa** [comment]
Hi @Joseph94m ,

Thanks for reaching us,
Yes, it is a typo, we will fix it.
The right parametter is "[custom_endpoint_oapi](https://developer.hashicorp.com/packer/plugins/builders/outscale/outscale-bsu#custom_endpoint_oapi)"

Best regards,
