### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by Joseph94m** [outscale/packer-plugin-outscale#176]
Hello @outscale-toa, the builders doc links are broken on 
https://developer.hashicorp.com/packer/integrations/outscale/outscale#builders

I guess they is because of the most recent commits in https://github.com/outscale/packer-plugin-outscale/tree/main/docs/builders

**Comment by outscale-mgo** [comment]
Hello,
https://developer.hashicorp.com/packer/integrations/outscale/outscale/latest/components/builder/bsuvolume
and other links to builders are now working.
So this is fixed.
