### ISSUE TITLE
Unable to mark an omi as public when no omi_account_ids specified

### ISSUE THREAD

**Issue by bnau** [outscale/packer-plugin-outscale#192]
#### Overview of the Issue

There is a parameter called `global_permission` marking an omi as public when set to `true`. It's handled during the update step. When `omi_account_ids` and `snapshot_account_ids` aren't specified, the step is completely skipped whatever the value of `global_permission`. Cf. step_update_omi.go line 38

#### Reproduction Steps

Set `global_permission` to `true` without setting `omi_account_ids`

### Plugin and Packer version

From `packer 1.2.0`

**Comment by outscale-toa** [comment]
Hi @bnau,

Thanks for reaching us, we are looking at your issue

Best regards,

**Comment by outscale-mgo** [comment]
Hello, I've made a PR, I wouldn't mind your configuration file, so I can test this.

Thanks for the issue.

**Comment by bnau** [comment]
Hello! Thanks for your answer. I have linked a configuration file. 
[public_image.pkr.zip](https://github.com/user-attachments/files/15806480/public_image.pkr.zip)
