### ISSUE TITLE
Explicit errors on missing parameters

### ISSUE THREAD

**Issue by RomLecat** [outscale/packer-plugin-outscale#54]
#### Description

When omitting certain parameters, such as region (either from env or conf), the error is not really explicit (it only produces malformed URL).
Packer could return a more explicit error to indicate the missing parameter(s).

#### Use Case(s)

N/A

#### Potential configuration

N/A

#### Potential References
See https://github.com/outscale/omi-packer/issues/3.

**Comment by outscale-mdr** [comment]
Hello @RomLecat,

Thank you for this idea. We will implement it as soon as possible.

Best regards,
Maxime
