### ISSUE TITLE
Support GlobalPermissions for the images

### ISSUE THREAD

**Issue by outscale-mdr** [outscale/packer-plugin-outscale#73]
Hello 👋,

I have seen that it was not possible to make the generated image publicly accessible. Is it possible to add a parameter to support this [API feature](https://docs.outscale.com/api#updateimage)?

Thank you !

**Comment by outscale-hmi** [comment]
Hello, 
PR is done https://github.com/outscale/packer-plugin-outscale/pull/79

**Comment by outscale-hmi** [comment]
PR done and merged
