### ISSUE TITLE
Unknown source type osc-bsusurrogate

### ISSUE THREAD

**Issue by clementcohen** [outscale/packer-plugin-outscale#76]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Error: Unknown source type osc-bsusurrogate

#### Reproduction Steps

use  the sample [osc-bsu.pkr.hcl](https://github.com/outscale/packer-plugin-outscale/blob/main/example/osc-bsu.pkr.hcl)

### Plugin and Packer version

Packer v1.8.3

### Simplified Packer Buildfile
sample directory in this project: [osc-bsu.pkr.hcl](https://github.com/outscale/packer-plugin-outscale/blob/main/example/osc-bsu.pkr.hcl)

### Operating system and Environment details

ubuntu on WSL

### Log Fragments and crash.log files

[gist](https://gist.github.com/clementcohen/e5ef720963c9e1d316d344a86baeb373)

**Comment by outscale-hmi** [comment]
Hi, 
Packer 1.8.3 independently does locate plugins in PACKER_HOME_DIR/plugins. Packer 1.7.10 with Packer SDK 0.3.1 will also locate plugins in PACKER_HOME_DIR/plugins. Packer 1.8.3 with Packer SDK 0.3.1 does NOT locate plugins in PACKER_HOME_DIR/plugins.

So this is actually an incompatibility between a recent update to Packer and possibly a necessary corresponding update to the Packer SDK.

You can find here the issue in Packer about this problem https://github.com/hashicorp/packer/issues/11972

**Comment by outscale-hmi** [comment]
Hi, 
Since Packer 1.8.3, our plugin is no longer bundled in the Packer binary, So all our resources are now named "outscale-resource" not osc-resource"
In this example, you should use "outscale-bsusurrogate" not "osc-bsusurrogate"

Documentation will be updated soon.

**Comment by clementcohen** [comment]
Hi, 
OKay it's working with  outscale-bsusurrogate instead of  osc-bsusurrogate thanks ;)*
I'm closing this issue
